# Generated by Django 4.0.1 on 2022-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.TextField()),
                ('newPos', models.IntegerField()),
                ('moneyChange', models.IntegerField()),
            ],
        ),
    ]
