# Generated by Django 4.0.1 on 2022-01-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactor',
            name='newPos',
        ),
        migrations.RemoveField(
            model_name='interactor',
            name='turn',
        ),
        migrations.AddField(
            model_name='interactor',
            name='housesBought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interactor',
            name='pos',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='interactor',
            name='propertyBought',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='interactor',
            name='moneyChange',
            field=models.IntegerField(default=0),
        ),
    ]
