# Generated by Django 4.0.1 on 2022-01-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactor', '0002_remove_interactor_newpos_remove_interactor_turn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactor',
            old_name='moneyChange',
            new_name='money',
        ),
        migrations.AddField(
            model_name='interactor',
            name='propertyExpanded',
            field=models.IntegerField(default=-1),
        ),
    ]
